version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: shopping
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - D:\minio\data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
